### ISSUE TITLE
Impossibilité de rejoindre les spectateurs

### ISSUE THREAD

**Issue by YoLaw** [YoLawSnowy/TheTowers-Reloaded#10]
Lorsque la partie a démarré, les nouveaux joueurs du serveur arrivent dans le spawn et ne peuvent pas rejoindre les spectateurs. 
Il serait d'ailleurs cool de pouvoir faire /tw team gui (Accessible à tous) qui permettrait à chaque joueur d'afficher le menu n'importe quand. 
De plus, il serait sympa de pouvoir choisir une équipe dans la mesure où il y a des lacunes d'effectifs liées à des rage-quit. 
Si une équipe est pleine, alors on ne peut pas rejoindre d'équipe, mais si il manque des joueurs alors on peut la rejoindre. 
Exception: les joueurs appartenant déjà à une équipe ne peuvent pas rejoindre une nouvelle équipe.

**Comment by Snowydvp** [comment]
On peut deja rejoindre une quipe en cours de partie.
Pour la commande ok mais faut pas pouvoir la larme aux joueurs rouge et bleu

**Comment by YoLaw** [comment]
Ne la donne pas aux joueurs, donne la juste aux personnes n'appartenant pas à une team! D'ailleurs il serait cool de placer automatiquement les joueurs non affiliés à une équipe en Spectateur au lancement!
