### ISSUE TITLE
Accelerer le jeu ..

### ISSUE THREAD

**Issue by Snowydvp** [YoLawSnowy/TheTowers-Reloaded#15]
Mourir directement dès qu'on tombe sous les piliers ...

**Comment by Snowydvp** [comment]
approuveé  ??

**Comment by YoLaw** [comment]
Oui excellente idée! Mais il faudrait définir la hauteur à laquelle on meure dans le config.yml!

**Comment by Snowydvp** [comment]
ouais ok !!!

**Comment by YoLaw** [comment]
Par contre ce serait cool de faire en sorte que la personne qui a poussé dans le vide choppe le kill. 
Par défaut, au bout d'un certain temps de chute le joueur est considéré comme "tombé dans le vide". 
Il faudrait que tu arrives à rallonger le temps de désactivation du mode PvP si tu vois ce que je veut dire...

**Comment by Snowydvp** [comment]
Je peux pas récuperer la personne quand il est mort d'une chute.

**Comment by YoLaw** [comment]
Alors il faut qu'on puisse configurer pour changer la hauteur... Par contre Hypixel arrivent a récupérer le Jill même quand on fait une chute de 100m...
