### ISSUE TITLE
Une commande pour substituer l'item des équipes

### ISSUE THREAD

**Issue by YoLaw** [YoLawSnowy/TheTowers-Reloaded#18]
Dans le cas où on n'a pas l'item pour rejoindre une équipe, j'avais proposé dans le #10 qu'on fasse la commande /tw team gui. 
Je pensais plutôt à la commande /join tout simplement. Ou encore /tw join.
Je pense que /join est le plus simple, et que rares seront les personnes qui auront un plugin devant executer cette commande avec TheTowers.

**Comment by Snowydvp** [comment]
ou alors au lieu de faire join <equipe>
on fait une autre commande qui affiche le menu...

**Comment by Snowydvp** [comment]
Parce que avec join faut mettre un certin nom d'equipe derrier et tout ...

**Comment by YoLaw** [comment]
La commande /join affiche le menu. Je me suis mal exprimé.
Par contre l'item sera toujours configuré pareil!

**Comment by Snowydvp** [comment]
donc on est sur de mettre la commande /join ??

**Comment by Snowydvp** [comment]
C'est fait, avec possibilité de le desactiver dans le config
