### ISSUE TITLE
Bugs de Map

### ISSUE THREAD

**Issue by Snowydvp** [YoLawSnowy/TheTowers-Reloaded#19]
Lorsque la map n'existe pas dans le dossier backup, le plugin est désactivé. Il se reactive lorsqu'on reload et que le problème est reglé

**Comment by YoLaw** [comment]
Le plugin devrait être activé mais afficher un message d'erreur au démarrage ce ne serait pas plus simple? Parce que les gens ne vont pas deviner que c'est à cause du fichier inexistant dans backup!
D'ailleurs il faut en reparler un peu du backup

**Comment by Snowydvp** [comment]
Si c'est ecrit ca change pas

**Comment by YoLaw** [comment]
A toi de voir... Il faut que ce soit bien évident pour l'utilisateur...

**Comment by Snowydvp** [comment]
C'est ecrit dans la console que le plugin se desactive. en plus iol le voit en rouge en faisant /pl

**Comment by YoLaw** [comment]
D'accord je te fais confiance ;)
