### ISSUE TITLE
Coffres incassables

### ISSUE THREAD

**Issue by YoLaw** [YoLawSnowy/TheTowers-Reloaded#21]
J'ai remarqué qu'on peut exploser les coffres avec la tnt! 
Stp ajoutes une option dans le config pour pouvoir empêcher l'option des coffres :)
J'ai joué avec un fdp de Bofur qui a éclaté nos coffres...

**Comment by Snowydvp** [comment]
Pour l'instant c'est impossible ya une methode dans spigot qui fonctionne pas
