### ISSUE TITLE
Mode Ultra-Hardcore

### ISSUE THREAD

**Issue by YoLaw** [YoLawSnowy/TheTowers-Reloaded#6]
J'ai pensé à ajouter une option dans le config.yml pour activer/désactiver le mode Ultra Hardcore.
Par défaut il serait placé sur false.

**Comment by Snowydvp** [comment]
Et genre en Hardcore dès qu'on meurt on est ban ???

**Comment by YoLaw** [comment]
Ca bousillerait le jeu... Je parle d'UH pour ne plus regénérer ;)

**Comment by Snowydvp** [comment]
ah ouais !!
yes !!

**Comment by YoLaw** [comment]
Et ouais! Ca pourrait être assez sympa!
