### ISSUE TITLE
Mob Spawning

### ISSUE THREAD

**Issue by YoLaw** [YoLawSnowy/TheTowers-Reloaded#8]
Pendant la partie, des mobs ont la fâcheuse habitude d'apparaître!
Seules alternative:
- Changer la difficulté en Peaceful
- Mettre des régions.
- Mettre un plugin multi world
=> Cependant pour les deux dernières alternatives elles ne fonctionnent qu'au premier lancement puisque ton plugin gère lui même le multiworld et qu'il regénère un nouveau monde à chaque fois. Conséquence les fichiers de région se suppriment et le plugin multiworld ne reconnaît pas le monde en temps que tel puisqu'il n'est pas chargé/déchargé comme celui ci l'exige.
- L'interdiction du spawn de mobs dans server.properties ne fonctionne pas puisque cela s'applique dans le monde chargé par défaut (Qui est celui du Spawn en général).

Seule verritable alternative: Ajouter une option dans config.yml (AllowMobSpawning) qui active/désactive le mob spawning dans le monde TheTowers, sans changer la difficulté.
Par défaut cette option serait sur false.

**Comment by Snowydvp** [comment]
T'es sur pour les mobs ?? normalement ils apparaissent pas j'ai mis un gamerule dans le worldgame

**Comment by Snowydvp** [comment]
Normalement on peut les faire apparaître qu'avec des oeufs ..

**Comment by YoLaw** [comment]
Sur et certain ils apparaissent

**Comment by Snowydvp** [comment]
Bizarre moi je les vois pas, j'ai mis le gamerule a false en +

**Comment by Snowydvp** [comment]
Mais je dois pas mettre en peaceful sinon on peut pas faire apparaître les oeufs

**Comment by YoLaw** [comment]
Yep! Bah essayes de voir

**Comment by Snowydvp** [comment]
POur l'instant je laisse comme ca et on en reparle si on revoit des mobs
